version: "3.8"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: motivium-bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - NODE_OPTIONS=${NODE_OPTIONS}
      - MAIN_GUILD_ID=${MAIN_GUILD_ID}
      - CURRENCY_DOLLAR_EXCHANGE_CHANNEL_IDS=${CURRENCY_DOLLAR_EXCHANGE_CHANNEL_IDS}
      - CURRENCY_BTC_CHANNEL_IDS=${CURRENCY_BTC_CHANNEL_IDS}
      - CURRENCY_ETH_CHANNEL_IDS=${CURRENCY_ETH_CHANNEL_IDS}
      - CURRENCY_SOL_CHANNEL_IDS=${CURRENCY_SOL_CHANNEL_IDS}
      - COIN_GECKO_API_KEY=${COIN_GECKO_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - AI_CHANNELS_IDS=${AI_CHANNELS_IDS}
      - AI_NEWS_CHANNELS_IDS=${AI_NEWS_CHANNELS_IDS}
      - TECH_NEWS_CHANNELS_IDS=${TECH_NEWS_CHANNELS_IDS}
      - SPACE_NEWS_CHANNELS_IDS=${SPACE_NEWS_CHANNELS_IDS}
      - BRAZIL_NEWS_CHANNELS_IDS=${BRAZIL_NEWS_CHANNELS_IDS}
      - ECONOMY_NEWS_CHANNELS_IDS=${ECONOMY_NEWS_CHANNELS_IDS}
      - DATABASE_URL=${DATABASE_URL}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      # Telegram Configuration
      - PROMOTIONS_ENABLED=${PROMOTIONS_ENABLED}
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_PHONE_NUMBER=${TELEGRAM_PHONE_NUMBER}
      - TELEGRAM_PASSWORD=${TELEGRAM_PASSWORD}
      - TELEGRAM_SESSION_STRING=${TELEGRAM_SESSION_STRING}
      # Promotions Channels
      - PROMOTIONS_CHANNELS_IDS=${PROMOTIONS_CHANNELS_IDS}
      - TELEGRAM_PROMOTIONS_CHANNELS=${TELEGRAM_PROMOTIONS_CHANNELS}
      - TECH_PROMOTIONS_CHANNELS_IDS=${TECH_PROMOTIONS_CHANNELS_IDS}
      - TECH_TELEGRAM_CHANNELS=${TECH_TELEGRAM_CHANNELS}
      - GAMING_PROMOTIONS_CHANNELS_IDS=${GAMING_PROMOTIONS_CHANNELS_IDS}
      - GAMING_TELEGRAM_CHANNELS=${GAMING_TELEGRAM_CHANNELS}
      - FITNESS_PROMOTIONS_CHANNELS_IDS=${FITNESS_PROMOTIONS_CHANNELS_IDS}
      - FITNESS_TELEGRAM_CHANNELS=${FITNESS_TELEGRAM_CHANNELS}
      - AUTOMOTIVE_PROMOTIONS_CHANNELS_IDS=${AUTOMOTIVE_PROMOTIONS_CHANNELS_IDS}
      - AUTOMOTIVE_TELEGRAM_CHANNELS=${AUTOMOTIVE_TELEGRAM_CHANNELS}
      - FASHION_PROMOTIONS_CHANNELS_IDS=${FASHION_PROMOTIONS_CHANNELS_IDS}
      - FASHION_TELEGRAM_CHANNELS=${FASHION_TELEGRAM_CHANNELS}
      - HOME_PROMOTIONS_CHANNELS_IDS=${HOME_PROMOTIONS_CHANNELS_IDS}
      - HOME_TELEGRAM_CHANNELS=${HOME_TELEGRAM_CHANNELS}
      - BUGS_PROMOTIONS_CHANNELS_IDS=${BUGS_PROMOTIONS_CHANNELS_IDS}
      - BUGS_TELEGRAM_CHANNELS=${BUGS_TELEGRAM_CHANNELS}
      - ALIEXPRESS_PROMOTIONS_CHANNELS_IDS=${ALIEXPRESS_PROMOTIONS_CHANNELS_IDS}
      - ALIEXPRESS_TELEGRAM_CHANNELS=${ALIEXPRESS_TELEGRAM_CHANNELS}
      - CUPONS_PROMOTIONS_CHANNELS_IDS=${CUPONS_PROMOTIONS_CHANNELS_IDS}
      - CUPONS_TELEGRAM_CHANNELS=${CUPONS_TELEGRAM_CHANNELS}
      - BEAUTY_PROMOTIONS_CHANNELS_IDS=${BEAUTY_PROMOTIONS_CHANNELS_IDS}
      - BEAUTY_TELEGRAM_CHANNELS=${BEAUTY_TELEGRAM_CHANNELS}
      - FOOD_PROMOTIONS_CHANNELS_IDS=${FOOD_PROMOTIONS_CHANNELS_IDS}
      - FOOD_TELEGRAM_CHANNELS=${FOOD_TELEGRAM_CHANNELS}
      - HARDWARE_PROMOTIONS_CHANNELS_IDS=${HARDWARE_PROMOTIONS_CHANNELS_IDS}
      - HARDWARE_TELEGRAM_CHANNELS=${HARDWARE_TELEGRAM_CHANNELS}
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: bitnami/postgresql:13
    container_name: motivium-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/bitnami/postgresql
    restart: unless-stopped
volumes:
  postgres_data:
