version: '3.8'
services:
  bot:
    build: .
    container_name: motivium-bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - NODE_OPTIONS=${NODE_OPTIONS}
      - MAIN_GUILD_ID=${MAIN_GUILD_ID}
      - CURRENCY_DOLLAR_EXCHANGE_CHANNEL_IDS=${CURRENCY_DOLLAR_EXCHANGE_CHANNEL_IDS}
      - CURRENCY_BTC_CHANNEL_IDS=${CURRENCY_BTC_CHANNEL_IDS}
      - COIN_GECKO_API_KEY=${COIN_GECKO_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - AI_CHANNELS_IDS=${AI_CHANNELS_IDS}
      - AI_NEWS_CHANNELS_IDS=${AI_NEWS_CHANNELS_IDS}
      - TECH_NEWS_CHANNELS_IDS=${TECH_NEWS_CHANNELS_IDS}
      - SPACE_NEWS_CHANNELS_IDS=${SPACE_NEWS_CHANNELS_IDS}
      - ECONOMY_NEWS_CHANNELS_IDS=${ECONOMY_NEWS_CHANNELS_IDS}
    restart: unless-stopped
