export enum PromotionCategory {
  GENERAL = 'GENERAL',
  TECH = 'TECH',
  GAMING = 'GAMING',
  FITNESS = 'FITNESS',
  AUTOMOTIVE = 'AUTOMOTIVE',
  FASHION = 'FASHION',
  HOME = 'HOME',
  BUGS = 'BUGS',
  ALIEXPRESS = 'ALIEXPRESS',
  CUPONS = 'CUPONS',
  BEAUTY = 'BEAUTY',
  FOOD = 'FOOD',
  HARDWARE = 'HARDWARE',
}

export interface PromotionConfig {
  category: PromotionCategory
  discordChannelIds: string[]
  telegramChannels: string[]
  keywords: string[]
  schedulePattern: string
  maxPromotionsPerExecution: number
  maxAgeMinutes?: number
}

export interface SmartKeywordConfig {
  primary: string[]
  secondary: string[]
  contextRequired: string[]
  exclusions: string[]
  combinations: string[][]
}

// Sistema inteligente de classificação por palavras-chave
export const SMART_KEYWORDS: Record<PromotionCategory, SmartKeywordConfig> = {
  [PromotionCategory.GENERAL]: {
    primary: [
      'promoção',
      'desconto',
      'oferta',
      'cupom',
      'grátis',
      'free',
      'promo',
      'barato',
      'liquidação',
      'sale',
      'deals',
      'r$',
      'reais',
      'preço',
      'valor',
    ],
    secondary: [
      'black friday',
      'cyber monday',
      '%',
      'off',
      'imperdível',
      'oportunidade',
      'último dia',
      'por tempo limitado',
      'frete grátis',
      'cashback',
      'economia',
      'economize',
      'baratinho',
      'promoções',
      'ofertas',
      'especial',
      'amazon',
      'amzn.to',
      'shopee',
      'mercado livre',
      'magalu',
      'magazine luiza',
      'casas bahia',
      'extra',
      'ponto',
      'submarino',
    ],
    contextRequired: [],
    exclusions: ['aliexpress', 'ali express'], // Excluir se for específico do AliExpress
    combinations: [
      ['r$', 'off'],
      ['preço', 'baixo'],
      ['oferta', 'especial'],
      ['link', 'amazon'],
      ['link', 'amzn.to'],
    ],
  },

  [PromotionCategory.TECH]: {
    primary: [
      'smartphone',
      'celular',
      'notebook',
      'laptop',
      'tablet',
      'monitor',
      'tv',
      'smartwatch',
      'tech',
      'tecnologia',
      'eletrônico',
      'gadget',
      'parafusadeira',
      'furadeira',
      'ferramenta elétrica',
    ],
    secondary: [
      'fone',
      'headset',
      'carregador',
      'cabo',
      'mouse',
      'teclado',
      'samsung',
      'apple',
      'xiaomi',
      'motorola',
      'lg',
      'bateria',
      'volt',
      'bivolt',
      'empunhadura',
      'maleta',
    ],
    contextRequired: [],
    exclusions: [
      'facas',
      'panela',
      'cozinha',
      'banheiro',
      'decoração',
      'móvel',
      'casa',
      'frigideira',
      'moletom',
      'roupa',
      'tênis',
      'camisa',
    ],
    combinations: [
      ['headset', 'gamer'],
      ['mouse', 'gamer'],
      ['teclado', 'gamer'],
      ['smart', 'tv'],
      ['smart', 'watch'],
      ['4k', 'tv'],
      ['8k', 'tv'],
      ['kit', 'acessórios'],
      ['ferramenta', 'bateria'],
      ['parafusadeira', 'furadeira'],
    ],
  },

  [PromotionCategory.GAMING]: {
    primary: [
      'game',
      'gaming',
      'gamer',
      'playstation',
      'xbox',
      'nintendo',
      'switch',
      'ps5',
      'ps4',
      'steam',
      'epic',
    ],
    secondary: ['controle', 'joystick', 'setup'],
    contextRequired: ['jogo'], // 'jogo' só conta se tiver contexto gamer
    exclusions: [
      'facas',
      'panela',
      'cozinha',
      'utensílio',
      'tramontina',
      'inox',
      'fire stick',
      'memoria ram',
      'fonte',
    ],
    combinations: [
      ['jogo', 'ps'],
      ['jogo', 'xbox'],
      ['jogo', 'nintendo'],
      ['jogo', 'steam'],
      ['jogo', 'epic'],
      ['headset', 'gamer'],
      ['cadeira', 'gamer'],
      ['mouse', 'gamer'],
      ['teclado', 'gamer'],
    ],
  },

  [PromotionCategory.FITNESS]: {
    primary: [
      'academia',
      'fitness',
      'treino',
      'whey',
      'protein',
      'suplemento',
      'creatina',
      'bcaa',
      'musculação',
      'crossfit',
      'corrida',
      'ciclismo',
      'esporte',
      'exercício',
      'atividade física',
    ],
    secondary: ['esteira', 'bicicleta', 'halteres', 'yoga', 'pilates', 'saúde'],
    contextRequired: [],
    exclusions: [],
    combinations: [['pre', 'treino']],
  },

  [PromotionCategory.AUTOMOTIVE]: {
    primary: ['automotivo', 'automotiva', 'carro', 'pneu', 'som automotivo', 'alarme', 'película'],
    secondary: ['oficina', 'combustível', 'revisão', 'seguro auto'],
    contextRequired: [],
    exclusions: [],
    combinations: [
      ['acessório', 'automotivo'],
      ['serviço', 'automotivo'],
      ['android', 'auto'],
      ['apple', 'carplay'],
    ],
  },

  [PromotionCategory.FASHION]: {
    primary: [
      'moda',
      'roupa',
      'tênis',
      'camisa',
      'vestido',
      'bolsa',
      'sapato',
      'fashion',
      'look',
      'calçado',
    ],
    secondary: [
      'jaqueta',
      'blusa',
      'calça',
      'short',
      'bermuda',
      'saia',
      'chinelo',
      'sandália',
      'relógio',
      'óculos',
      'bijuteria',
    ],
    contextRequired: [],
    exclusions: ['panela', 'cozinha', 'utensílio', 'eletrodoméstico', 'sabonete', 'shampoo', 'sabao'],
    combinations: [],
  },

  [PromotionCategory.HOME]: {
    primary: ['casa', 'decoração', 'móvel', 'eletrodoméstico', 'cozinha', 'banheiro'],
    secondary: [
      'sofá',
      'mesa',
      'cadeira',
      'organizador',
      'iluminação',
      'tapete',
      'cama',
      'armário',
      'geladeira',
      'airfryer',
      'fogão',
      'microondas',
      'aspirador',
      'ferro',
      'liquidificador',
      'panela',
      'utensílio',
      'decorativo',
      'cortina',
      'colchão',
      'travesseiro',
      'edredom',
      'toalha',
      'almofada',
      'prateleira',
      'luminária',
      'ventilador',
      'ar condicionado',
    ],
    contextRequired: [],
    exclusions: ['gamer', 'gaming', 'playstation', 'xbox', 'casas bahia'],
    combinations: [
      ['eletro', 'doméstico'],
      ['utensílio', 'cozinha'],
      ['utensílio', 'doméstico'],
      ['porta', 'copo'],
      ['porta', 'temperos'],
    ],
  },

  [PromotionCategory.BUGS]: {
    primary: ['bug', 'bugs'],
    secondary: [],
    contextRequired: [],
    exclusions: [],
    combinations: [],
  },

  [PromotionCategory.ALIEXPRESS]: {
    primary: ['aliexpress'],
    secondary: ['ali express', 'aliex'],
    contextRequired: [],
    exclusions: ['amazon', 'amzn.to', 'shopee', 'mercado livre', 'magalu', 'magazine luiza'],
    combinations: [],
  },

  [PromotionCategory.CUPONS]: {
    primary: ['cupom', 'cupons'],
    secondary: ['vale', 'voucher', 'cashback'],
    contextRequired: [],
    exclusions: [],
    combinations: [],
  },

  [PromotionCategory.BEAUTY]: {
    primary: [
      'beleza',
      'cosméticos',
      'maquiagem',
      'perfume',
      'skincare',
      'cuidados pessoais',
      'cabelo',
      'shampoo',
      'condicionador',
      'creme',
      'hidratante',
    ],
    secondary: [
      'batom',
      'base',
      'rímel',
      'blush',
      'pó compacto',
      'sombra',
      'esmalte',
      'unha',
      'pele',
      'rosto',
      'corpo',
      'sephora',
      'natura',
      'avon',
      'boticário',
      'loreal',
    ],
    contextRequired: [],
    exclusions: [
      'casa',
      'cozinha',
      'banheiro',
      'parafusadeira',
      'furadeira',
      'ferramenta',
      'elétrica',
      'bateria',
      'volt',
      'v',
      'kit',
      'acessórios',
      'maleta',
      'empunhadura',
      'bivolt',
    ],
    combinations: [
      ['kit', 'beleza'],
      ['cuidados', 'pessoais'],
      ['produtos', 'beleza'],
      ['itens', 'beleza'],
    ],
  },

  [PromotionCategory.FOOD]: {
    primary: [
      'comida',
      'delivery',
      'restaurante',
      'ifood',
      'uber eats',
      'rappi',
      'food',
      'pizza',
      'hambúrguer',
      'lanche',
      'refeição',
      'café',
      'doce',
      'salgado',
      'bebida',
      'drink',
      'cerveja',
      'vinho',
      'whisky',
      'heineken',
      'budweiser',
      'amstel',
      'pepsi',
      'coca-cola',
      'hemmer',
    ],
    secondary: ['menu', 'cardápio', 'pedido', 'delivery grátis', 'heinz'],
    contextRequired: [],
    exclusions: ['copo'],
    combinations: [['cupom', 'delivery']],
  },

  [PromotionCategory.HARDWARE]: {
    primary: [
      'placa de vídeo',
      'gpu',
      'placa mãe',
      'motherboard',
      'processador',
      'cpu',
      'memória ram',
      'ram',
      'ssd',
      'hd',
      'hard disk',
      'fonte',
      'power supply',
      'cooler',
      'water cooler',
      'gabinete',
      'case',
      'pc gamer',
      'setup gamer',
    ],
    secondary: [
      'nvidia',
      'amd',
      'intel',
      'ryzen',
      'core i5',
      'core i7',
      'core i9',
      'geforce',
      'radeon',
      'rtx',
      'gtx',
      'rx',
      'ddr4',
      'ddr5',
      'nvme',
      'sata',
      'm.2',
      'terabyte',
      'gigabyte',
      'corsair',
      'asus',
      'msi',
      'gigabyte',
      'asrock',
      'evga',
      'seasonic',
      'thermaltake',
      'noctua',
      'arctic',
      'fractal design',
      'nzxt',
      'rgb',
      'argb',
      '80 plus',
      'modular',
      'semi modular',
      'atx',
      'micro atx',
      'mini itx',
      'socket',
      'lga',
      'am4',
      'am5',
      'pcie',
      'usb 3.0',
      'usb-c',
      'wifi',
      'bluetooth',
      'overclock',
      'oc',
      'gaming',
      'gamer',
    ],
    contextRequired: [],
    exclusions: [
      'notebook',
      'laptop',
      'tablet',
      'smartphone',
      'celular',
      'monitor',
      'tv',
      'smartwatch',
      'fone',
      'headset',
      'mouse',
      'teclado',
      'cabo',
      'carregador',
      'capa',
      'película',
      'suporte',
      'cadeira',
      'iphone',
      'cooktop',
    ],
    combinations: [
      ['placa', 'vídeo'],
      ['placa', 'mãe'],
      ['memória', 'ram'],
      ['water', 'cooler'],
      ['pc', 'gamer'],
      ['setup', 'gamer'],
      ['fonte', 'modular'],
      ['ssd', 'nvme'],
      ['hd', 'sata'],
      ['80', 'plus'],
      ['core', 'i5'],
      ['core', 'i7'],
      ['core', 'i9'],
      ['ddr4', 'ram'],
      ['ddr5', 'ram'],
      ['rtx', '4090'],
      ['rtx', '4080'],
      ['rtx', '4070'],
      ['rtx', '3080'],
      ['rtx', '3070'],
      ['rtx', '3060'],
      ['gtx', '1660'],
      ['rx', '7900'],
      ['rx', '6800'],
      ['rx', '6700'],
      ['ryzen', '7'],
      ['ryzen', '5'],
      ['ryzen', '9'],
    ],
  },
}

// ── Centralized Category Metadata ────────────────────────────
// Single source of truth for emojis, display names, and env var keys.
// Used by promotions.service.ts and command files to avoid repetition.
export interface CategoryMeta {
  emoji: string
  name: string
  discordEnv: string
  telegramEnv: string
}

export const CATEGORY_METADATA: Record<PromotionCategory, CategoryMeta> = {
  [PromotionCategory.GENERAL]: { emoji: '🎯', name: 'Geral', discordEnv: 'PROMOTIONS_CHANNELS_IDS', telegramEnv: 'TELEGRAM_PROMOTIONS_CHANNELS' },
  [PromotionCategory.TECH]: { emoji: '💻', name: 'Tech', discordEnv: 'TECH_PROMOTIONS_CHANNELS_IDS', telegramEnv: 'TECH_TELEGRAM_CHANNELS' },
  [PromotionCategory.GAMING]: { emoji: '🎮', name: 'Gaming', discordEnv: 'GAMING_PROMOTIONS_CHANNELS_IDS', telegramEnv: 'GAMING_TELEGRAM_CHANNELS' },
  [PromotionCategory.FITNESS]: { emoji: '🏋️', name: 'Fitness', discordEnv: 'FITNESS_PROMOTIONS_CHANNELS_IDS', telegramEnv: 'FITNESS_TELEGRAM_CHANNELS' },
  [PromotionCategory.AUTOMOTIVE]: { emoji: '🚗', name: 'Automotivo', discordEnv: 'AUTOMOTIVE_PROMOTIONS_CHANNELS_IDS', telegramEnv: 'AUTOMOTIVE_TELEGRAM_CHANNELS' },
  [PromotionCategory.FASHION]: { emoji: '👗', name: 'Moda', discordEnv: 'FASHION_PROMOTIONS_CHANNELS_IDS', telegramEnv: 'FASHION_TELEGRAM_CHANNELS' },
  [PromotionCategory.HOME]: { emoji: '🏠', name: 'Casa', discordEnv: 'HOME_PROMOTIONS_CHANNELS_IDS', telegramEnv: 'HOME_TELEGRAM_CHANNELS' },
  [PromotionCategory.BUGS]: { emoji: '🐛', name: 'Bugs', discordEnv: 'BUGS_PROMOTIONS_CHANNELS_IDS', telegramEnv: 'BUGS_TELEGRAM_CHANNELS' },
  [PromotionCategory.ALIEXPRESS]: { emoji: '🛒', name: 'AliExpress', discordEnv: 'ALIEXPRESS_PROMOTIONS_CHANNELS_IDS', telegramEnv: 'ALIEXPRESS_TELEGRAM_CHANNELS' },
  [PromotionCategory.CUPONS]: { emoji: '🎫', name: 'Cupons', discordEnv: 'CUPONS_PROMOTIONS_CHANNELS_IDS', telegramEnv: 'CUPONS_TELEGRAM_CHANNELS' },
  [PromotionCategory.BEAUTY]: { emoji: '💄', name: 'Beleza', discordEnv: 'BEAUTY_PROMOTIONS_CHANNELS_IDS', telegramEnv: 'BEAUTY_TELEGRAM_CHANNELS' },
  [PromotionCategory.FOOD]: { emoji: '🍕', name: 'Food', discordEnv: 'FOOD_PROMOTIONS_CHANNELS_IDS', telegramEnv: 'FOOD_TELEGRAM_CHANNELS' },
  [PromotionCategory.HARDWARE]: { emoji: '🖥️', name: 'Hardware', discordEnv: 'HARDWARE_PROMOTIONS_CHANNELS_IDS', telegramEnv: 'HARDWARE_TELEGRAM_CHANNELS' },
}

// ── Promotion Config ─────────────────────────────────────────

export const DEFAULT_PROMOTION_CONFIG: Omit<
  PromotionConfig,
  'category' | 'discordChannelIds' | 'telegramChannels' | 'keywords'
> = {
  schedulePattern: '*/1 * * * *',
  maxPromotionsPerExecution: 1,
  maxAgeMinutes: 5,
}

// Only categories that differ from the default maxAgeMinutes (5 min)
const CATEGORY_MAX_AGE_OVERRIDES: Partial<Record<PromotionCategory, number>> = {
  [PromotionCategory.AUTOMOTIVE]: 60,
  [PromotionCategory.HOME]: 60,
  [PromotionCategory.ALIEXPRESS]: 15,
  [PromotionCategory.CUPONS]: 15,
  [PromotionCategory.BEAUTY]: 30,
  [PromotionCategory.FOOD]: 10,
  [PromotionCategory.HARDWARE]: 30,
}

// Build full per-category config by merging defaults with overrides
export const CATEGORY_SPECIFIC_CONFIG: Record<
  PromotionCategory,
  Pick<PromotionConfig, 'schedulePattern' | 'maxPromotionsPerExecution' | 'maxAgeMinutes'>
> = Object.values(PromotionCategory).reduce(
  (acc, category) => {
    acc[category] = {
      ...DEFAULT_PROMOTION_CONFIG,
      maxAgeMinutes: CATEGORY_MAX_AGE_OVERRIDES[category] ?? DEFAULT_PROMOTION_CONFIG.maxAgeMinutes!,
    }
    return acc
  },
  {} as Record<PromotionCategory, Pick<PromotionConfig, 'schedulePattern' | 'maxPromotionsPerExecution' | 'maxAgeMinutes'>>,
)

// Função para extrair todas as palavras-chave para compatibilidade
export const PROMOTION_KEYWORDS: Record<PromotionCategory, readonly string[]> = Object.entries(
  SMART_KEYWORDS,
).reduce(
  (acc, [category, config]) => {
    acc[category as PromotionCategory] = [
      ...config.primary,
      ...config.secondary,
    ] as readonly string[]
    return acc
  },
  {} as Record<PromotionCategory, readonly string[]>,
)
